version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: nest-xp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
